### PR TITLE
Use alt-ergo 2.5

### PR DESCRIPTION
**Pull request by vbgl**

### CODE REVIEW

**Comment by vbgl** [comment]
Note that I don’t know how to update the docker image that is used in CI. Why isn’t it part of this repo?

**Comment by strub** [comment]
I think it is using the EasyCrypt Docker image. The Docker file is in the EasyCrypt repository.

**Comment by vbgl** [comment]
So is there any hope for this CI to work?

**Comment by vbgl** [comment]
Alright. I’ve thus amended the CI job script to install the required version of alt-ergo on every run. It seems to work:
https://github.com/vbgl/hakyber/actions/runs/8295929534

**Comment by strub** [comment]
In fact, I don't understand from where the Docker image comes. The EC one contains Alt-Ergo 2.4 & 2.5...

**Comment by strub** [comment]
Let's wait for that.

https://github.com/formosa-crypto/hakyber/pull/34

**Review by strub — APPROVED** [review]

**Pull request merged**
